services:
  mariadb:
    image: mariadb:10.4.7
    container_name: microservice-mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      TZ: Asia/Taipei
    ports:
      - "3308:3306" # 主機端口:容器端口
    volumes:
      - D:/Codes/GoStudy/mariadb-data:/var/lib/mysql # 資料持久化
    command: mysqld --sql_mode="IGNORE_SPACE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
    # command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0
    # networks:
    #   - app-network # 加入共用網絡
    labels:
      - "service=database" # 標籤，方便管理和識別

  phpmyadmin:
    image: phpmyadmin:5.2.1
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mariadb # 使用服務名稱 mariadb 作為主機名，透過 Docker DNS 解析
      PMA_PORT: 3306
      UPLOAD_LIMIT: 2G
      MEMORY_LIMIT: 2048M
      MAX_EXECUTION_TIME: 600
      MAX_INPUT_TIME: 600
    ports:
      - "8888:80" # 主機端口:容器端口
    depends_on:
      - mariadb # 依賴 mariadb 服務先啟動
    # networks:
    #   - app-network # 加入共用網絡
    labels:
      - "service=admin-tool" # 標籤，方便管理和識別