// ==========================================================================
// Code generated and maintained by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.4
// source: pbentity/users.proto

package pbentity

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Users struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`              //
	Username      string                 `protobuf:"bytes,2,opt,name=Username,proto3" json:"Username,omitempty"`   //
	Password      string                 `protobuf:"bytes,3,opt,name=Password,proto3" json:"Password,omitempty"`   //
	Email         string                 `protobuf:"bytes,4,opt,name=Email,proto3" json:"Email,omitempty"`         //
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"` //
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"` //
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Users) Reset() {
	*x = Users{}
	mi := &file_pbentity_users_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Users) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Users) ProtoMessage() {}

func (x *Users) ProtoReflect() protoreflect.Message {
	mi := &file_pbentity_users_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Users.ProtoReflect.Descriptor instead.
func (*Users) Descriptor() ([]byte, []int) {
	return file_pbentity_users_proto_rawDescGZIP(), []int{0}
}

func (x *Users) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Users) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Users) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Users) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Users) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Users) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_pbentity_users_proto protoreflect.FileDescriptor

const file_pbentity_users_proto_rawDesc = "" +
	"\n" +
	"\x14pbentity/users.proto\x12\bpbentity\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd9\x01\n" +
	"\x05Users\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\rR\x02Id\x12\x1a\n" +
	"\bUsername\x18\x02 \x01(\tR\bUsername\x12\x1a\n" +
	"\bPassword\x18\x03 \x01(\tR\bPassword\x12\x14\n" +
	"\x05Email\x18\x04 \x01(\tR\x05Email\x128\n" +
	"\tCreatedAt\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tCreatedAt\x128\n" +
	"\tUpdatedAt\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tUpdatedAtB\x1fZ\x1dproxima/app/user/api/pbentityb\x06proto3"

var (
	file_pbentity_users_proto_rawDescOnce sync.Once
	file_pbentity_users_proto_rawDescData []byte
)

func file_pbentity_users_proto_rawDescGZIP() []byte {
	file_pbentity_users_proto_rawDescOnce.Do(func() {
		file_pbentity_users_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pbentity_users_proto_rawDesc), len(file_pbentity_users_proto_rawDesc)))
	})
	return file_pbentity_users_proto_rawDescData
}

var file_pbentity_users_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pbentity_users_proto_goTypes = []any{
	(*Users)(nil),                 // 0: pbentity.Users
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_pbentity_users_proto_depIdxs = []int32{
	1, // 0: pbentity.Users.CreatedAt:type_name -> google.protobuf.Timestamp
	1, // 1: pbentity.Users.UpdatedAt:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pbentity_users_proto_init() }
func file_pbentity_users_proto_init() {
	if File_pbentity_users_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pbentity_users_proto_rawDesc), len(file_pbentity_users_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pbentity_users_proto_goTypes,
		DependencyIndexes: file_pbentity_users_proto_depIdxs,
		MessageInfos:      file_pbentity_users_proto_msgTypes,
	}.Build()
	File_pbentity_users_proto = out.File
	file_pbentity_users_proto_goTypes = nil
	file_pbentity_users_proto_depIdxs = nil
}
